# Import the package
library(spartan)
# Folder containing the Netlogo Behaviour Space table,
# and where the processed results will be written to
FILEPATH<-"/home/kja505/Documents/Spartan3_Test_Data/Netlogo/LHC/Analysis/"
# Name of the result file generated by Netlogo. Note no file extension
# The number of the sample is added on to this (i.e. for parameter set 1),
# spartan will make this lhcResult1.csv
LHCSAMPLE_RESULTFILENAME<-"lhcResult"
# Location of a file containing the parameter value sets
# generated by the hypercube sampling (i.e. the file generated
# in the previous method of this tutorial.
SPARTAN_PARAMETER_FILE<-"LHC_Parameters_for_Runs.csv"
# Number of parameter samples generated from the hypercube
NUMSAMPLES<-500
# The simulation output measures being examined. Should be specified
# as they are in the Netlogo file
MEASURES<-c("death-thru-sickness","death-but-immune","death-old-age",
            "death-old-and-sick")
# File name to give to the summary file that is produced showing
# the parameter value sets alongside the median results for each
# simulation output measure.
LHC_ALL_SIM_RESULTS_FILE<-"Virus_LHCSummary.csv"
# Timestep of interest. The behaviour space table is likely to contain
# all timesteps - this narrows the analysis
TIMESTEP<-5200
# Parameters of interest in this analysis
PARAMETERS<-c("infectiousness","chance-recover","duration")
# What each measure represents. Used in graphing results
MEASURE_SCALE<-c("Number of People","Number of People",
                 "Number of People","Number of People")
# File name to give to the file showing the Partial Rank Correlation
# Coefficients for each parameter. Again note no file extension
CORCOEFFSOUTPUTFILE<-"EgSet_corCoeffs"
# Not used in this case, but when a simulation is analysed at
# multiple timepoints (see Tutorials 1-4)
TIMEPOINTS<-NULL; TIMEPOINTSCALE<-NULL

lhc_process_netlogo_result(FILEPATH, LHCSAMPLE_RESULTFILENAME, SPARTAN_PARAMETER_FILE, NUMSAMPLES, MEASURES, LHC_ALL_SIM_RESULTS_FILE, TIMESTEP)

lhc_generatePRCoEffs(FILEPATH, PARAMETERS, MEASURES, LHC_ALL_SIM_RESULTS_FILE, CORCOEFFSOUTPUTFILE)

lhc_graphMeasuresForParameterChange(FILEPATH, PARAMETERS, MEASURES, MEASURE_SCALE, CORCOEFFSOUTPUTFILE, LHC_ALL_SIM_RESULTS_FILE)
